### ISSUE TITLE
Create application mockups

### ISSUE THREAD

**Issue by daniloaf** [daniloaf/moviesnetwork#6]

**Comment by brenopolanski** [comment]
Hey @daniloaf 

I created a version of mockup very simple, I just added your ideas.

**Mockup V1:**

![v1](https://cloud.githubusercontent.com/assets/1894191/11643884/a4e29ec6-9d25-11e5-9e5b-e16b9be4d724.png)

**Comment by brenopolanski** [comment]
New mockup... sorry for this image :stuck_out_tongue_winking_eye:

![wp_20151209_19_54_14_pro](https://cloud.githubusercontent.com/assets/1894191/11701612/4ce8c250-9eaf-11e5-9a59-a14bce99f160.jpg)
